import { chromium } from '@playwright/test'
const b = await chromium.launch()
const ctx = await b.newContext({ viewport: { width: 1280, height: 800 }, baseURL: 'http://localhost:5173' })
const page = await ctx.newPage()
await page.goto('/login', { waitUntil: 'domcontentloaded' })
await page.waitForLoadState('networkidle').catch(()=>{})
await page.locator('input[type="email"]').fill('admin@nubi.dev')
await page.locator('input[type="password"]').fill('nubi-admin-2026')
await page.locator('button[type="submit"]').click()
await page.waitForURL(u => !u.pathname.startsWith('/login'), { timeout: 40000 })
await page.goto('/editor', { waitUntil: 'domcontentloaded' })
await page.getByTestId('palette-add-kpi').click({ timeout: 20000 }).catch(()=>{})
await page.waitForTimeout(1500)
await page.screenshot({ path: '/tmp/editor-new.png' })
console.log('device-switcher count:', await page.getByTestId('device-switcher').count())
await b.close()
