"""Shared demo-content loader — the single source of truth for demo dashboards.

The demo workspace (queries + dashboards) is defined declaratively as JSON files
under ``backend/seed_data/demo/`` so the content lives in versioned files rather
than hardcoded Python:

  - ``queries.json`` : ``{logical_key: {name, sql, params}}``
  - ``boards.json``  : ``[{seed_id, name, starter, spec}, ...]`` where every widget
    references a query by the ``"@<logical_key>"`` placeholder (resolved to the
    real query UUID at seed time).

The DATA behind those dashboards is four deterministic datasets (17 tables,
generated by ``seed_data/generators/``) distributed as **parquet files** and
exposed through a single, real ``duckdb`` datastore whose ``view_sql`` creates
one view per table over ``read_parquet(...)`` — exactly like a user-created
DuckDB connector, with no demo special-casing in the query pipeline:

- **S3 configured** (``S3_ACCESS_KEY`` / ``AWS_ACCESS_KEY_ID`` env vars):
  parquet is exported per-project to
  ``s3://<bucket>/projects/<project_id>/demo/<dataset>/<table>.parquet``
  (``export_demo_to_s3`` + ``s3_datastore_config``).

- **No S3** (offline dev / CI): parquet is written once to the deterministic
  local directory ``backend/seed_data/parquet/<dataset>/<table>.parquet``
  (``export_demo_parquet_local`` + ``local_parquet_datastore_config``) — local
  mode goes through the same parquet + views path as S3 mode.

Two consumers share this loader:
  - ``seed.py --demo`` (superuser): materialises ALL boards.
  - ``app/sample.py`` (per project): seeds the full demo bundle on signup /
    project creation (removable; everything tagged ``sample=true``).
"""

from __future__ import annotations

import json
import os
from pathlib import Path
from typing import Any

from seed_data.generators import ALL_TABLES, DATASET_TABLES

_SEED_DATA_DIR = Path(__file__).resolve().parent.parent / "seed_data"
_DEMO_DIR = _SEED_DATA_DIR / "demo"

# Default local parquet export directory (gitignored, generated on demand).
LOCAL_PARQUET_DIR = _SEED_DATA_DIR / "parquet"

# Legacy alias: the retail star-schema tables (the original demo dataset).
DEMO_TABLES: tuple[str, ...] = DATASET_TABLES["retail_sales"]

# All 17 demo tables across the four datasets.
ALL_DEMO_TABLES: tuple[str, ...] = ALL_TABLES


# ---------------------------------------------------------------------------
# Demo fixture loaders
# ---------------------------------------------------------------------------


def load_queries() -> dict[str, dict[str, Any]]:
    """Return ``{logical_key: {name, sql, params}}`` from queries.json."""
    with open(_DEMO_DIR / "queries.json") as f:
        return json.load(f)


def load_boards(starter_only: bool = False) -> list[dict[str, Any]]:
    """Return board fixtures ``[{seed_id, name, starter, spec}, ...]``."""
    with open(_DEMO_DIR / "boards.json") as f:
        boards = json.load(f)
    return [b for b in boards if b.get("starter")] if starter_only else boards


def referenced_query_keys(boards: list[dict[str, Any]]) -> list[str]:
    """Logical query keys referenced by the given boards (via ``@key`` placeholders)."""
    keys: set[str] = set()

    def walk(node: Any) -> None:
        if isinstance(node, str):
            if node.startswith("@"):
                keys.add(node[1:])
        elif isinstance(node, dict):
            for v in node.values():
                walk(v)
        elif isinstance(node, list):
            for v in node:
                walk(v)

    for b in boards:
        walk(b["spec"])
    return sorted(keys)


def resolve_placeholders(spec: Any, idmap: dict[str, str]) -> Any:
    """Deep-copy *spec*, replacing every ``"@key"`` string with ``idmap["@key"]``.

    Unknown placeholders resolve to ``""`` (an empty query_id renders as a
    "needs configuration" widget rather than crashing).
    """
    if isinstance(spec, str):
        return idmap.get(spec, "") if spec.startswith("@") else spec
    if isinstance(spec, dict):
        return {k: resolve_placeholders(v, idmap) for k, v in spec.items()}
    if isinstance(spec, list):
        return [resolve_placeholders(v, idmap) for v in spec]
    return spec


# ---------------------------------------------------------------------------
# Legacy .duckdb file path (seed.py --demo offline fallback / tooling)
# ---------------------------------------------------------------------------


def sample_db_path() -> str:
    """Absolute path to the bundled demo DuckDB file, (re)building if needed.

    Rebuilds when the file is absent OR is missing any of the 17 demo tables
    (e.g. a stale file from before the multi-dataset demo).
    """
    from seed_data_duckdb import SAMPLE_DB_PATH, build_duckdb_file  # noqa: PLC0415

    path = os.path.abspath(SAMPLE_DB_PATH)
    if not os.path.exists(path):
        build_duckdb_file(path)
        return path

    # Verify the existing file has every expected table; rebuild otherwise.
    try:
        import duckdb  # noqa: PLC0415

        con = duckdb.connect(database=path, read_only=True)
        try:
            have = {r[0] for r in con.execute("SHOW TABLES").fetchall()}
        finally:
            con.close()
        if not set(ALL_DEMO_TABLES) <= have:
            build_duckdb_file(path)
    except Exception:  # noqa: BLE001 — unreadable/corrupt file: rebuild
        build_duckdb_file(path)
    return path


# ---------------------------------------------------------------------------
# Local parquet export (offline / no-S3 distribution path)
# ---------------------------------------------------------------------------


def _parquet_local_path(dataset: str, table: str, base_dir: Path) -> Path:
    return base_dir / dataset / f"{table}.parquet"


def export_demo_parquet_local(
    force: bool = False,
    base_dir: str | os.PathLike | None = None,
) -> dict[str, str]:
    """Write every demo table to local parquet files; return ``{table: abs_path}``.

    Files land under ``<base_dir>/<dataset>/<table>.parquet`` (default:
    ``backend/seed_data/parquet/``).  Idempotent — existing files are kept
    unless ``force=True``; a dataset is only generated when at least one of
    its files is missing, so repeat seeds are cheap.
    """
    import pyarrow.parquet as pq  # noqa: PLC0415

    from seed_data.generators import build_dataset  # noqa: PLC0415

    base = Path(base_dir) if base_dir is not None else LOCAL_PARQUET_DIR
    paths: dict[str, str] = {}
    for dataset, tables in DATASET_TABLES.items():
        targets = {t: _parquet_local_path(dataset, t, base) for t in tables}
        if force or not all(p.exists() for p in targets.values()):
            built = build_dataset(dataset)
            (base / dataset).mkdir(parents=True, exist_ok=True)
            for t, p in targets.items():
                if force or not p.exists():
                    pq.write_table(built[t], p)
        paths.update({t: str(p.resolve()) for t, p in targets.items()})
    return paths


def local_parquet_datastore_config(
    base_dir: str | os.PathLike | None = None,
) -> dict[str, Any]:
    """``duckdb`` datastore config reading all 17 demo tables from local parquet.

    The config mirrors the S3 variant exactly — ``database=":memory:"`` plus a
    multi-statement ``view_sql`` of ``CREATE VIEW <t> AS SELECT * FROM
    read_parquet('<abs path>')`` — so the normal connector → /query →
    /data-browser pipeline serves it with zero special-casing.  Call
    ``export_demo_parquet_local()`` first so the files exist.
    """
    base = Path(base_dir) if base_dir is not None else LOCAL_PARQUET_DIR

    view_statements: list[str] = []
    for dataset, tables in DATASET_TABLES.items():
        for table in tables:
            path = _parquet_local_path(dataset, table, base).resolve()
            view_statements.append(
                f"CREATE OR REPLACE VIEW {table} AS SELECT * FROM read_parquet('{path}')"
            )

    return {
        "connector_type": "duckdb",
        "database": ":memory:",
        "view_sql": ";\n".join(view_statements),
        "description": (
            "Demo datasets (retail sales, SaaS metrics, web analytics, finance ops) "
            "backed by local parquet files."
        ),
        "demo_local_dir": str(base),
        "sample": True,
        # Internal: backs the demo dashboards/queries by id. The connectors list
        # surfaces the branded virtual "Demo data" connector instead of this raw
        # row, so flag it system so list_connectors hides it (no duplicate card).
        "system": True,
    }


# ---------------------------------------------------------------------------
# S3 helpers
# ---------------------------------------------------------------------------


def _s3_is_configured() -> bool:
    """Return ``True`` when env vars supply enough S3/MinIO config to write parquet.

    Checks for an access key via the ``S3_ACCESS_KEY`` / ``AWS_ACCESS_KEY_ID``
    env-var families — necessary for any authenticated write to MinIO or AWS S3.
    ``NUBI_BUCKET_URI`` alone (without creds) is not sufficient when the bucket
    requires authentication.
    """
    access_key = (
        os.getenv("S3_ACCESS_KEY")
        or os.getenv("AWS_ACCESS_KEY_ID")
        or ""
    )
    return bool(access_key)


def _s3_bucket() -> str:
    """Return the S3 bucket name to use for demo parquet storage.

    Resolution order:
    1. ``NUBI_BUCKET_URI`` (e.g. ``s3://nubi``) — parse the bucket segment.
    2. ``NUBI_BUCKET_NAME`` — explicit bucket name.
    3. ``"nubi"`` — hard-coded default (matches local MinIO convention).
    """
    bucket_uri = os.getenv("NUBI_BUCKET_URI", "")
    if bucket_uri.startswith("s3://"):
        # e.g. "s3://nubi" → "nubi"; "s3://nubi/some/prefix" → "nubi"
        after_scheme = bucket_uri[len("s3://"):]
        return after_scheme.split("/")[0] or "nubi"

    return os.getenv("NUBI_BUCKET_NAME", "nubi")


def _s3_endpoint() -> str:
    """Return the S3 endpoint URL (empty string for AWS S3)."""
    return (
        os.getenv("S3_ENDPOINT_URL")
        or os.getenv("AWS_ENDPOINT_URL")
        or ""
    )


# ---------------------------------------------------------------------------
# S3 export
# ---------------------------------------------------------------------------


def _parquet_s3_uri(project_id: str, dataset: str, table: str, bucket: str) -> str:
    """Return the canonical S3 URI for a demo table parquet file."""
    return f"s3://{bucket}/projects/{project_id}/demo/{dataset}/{table}.parquet"


def export_demo_to_s3(
    project_id: str,
    bucket: str | None = None,
    force: bool = False,
) -> dict[str, str]:
    """Export all four demo datasets to per-project S3 parquet files.

    Uses DuckDB ``COPY (SELECT * FROM <arrow table>) TO 's3://...'`` with
    httpfs + S3 SECRET configured by ``setup_s3_httpfs``.

    Idempotent — skips tables whose parquet file already exists in S3 unless
    ``force=True``.  The skip check is a try/read: if the parquet is readable
    the table is considered present.  Each dataset is only *generated* when at
    least one of its tables actually needs writing.

    Returns ``{table: s3_uri}`` for every table written (skipped tables absent).
    """
    import duckdb  # noqa: PLC0415

    from app.connectors.duckdb_conn import setup_s3_httpfs  # noqa: PLC0415
    from seed_data.generators import build_dataset  # noqa: PLC0415

    bucket = bucket or _s3_bucket()

    write_conn = duckdb.connect(database=":memory:")
    setup_s3_httpfs(write_conn)

    written: dict[str, str] = {}
    try:
        for dataset, tables in DATASET_TABLES.items():
            built = None  # generated lazily, only when a table needs writing
            for table in tables:
                uri = _parquet_s3_uri(project_id, dataset, table, bucket)

                if not force:
                    # Idempotency check — try to read the first row.
                    try:
                        write_conn.execute(
                            f"SELECT * FROM read_parquet('{uri}') LIMIT 1"
                        ).fetchone()
                        continue  # already exists; skip
                    except Exception:
                        pass  # not present or unreadable — proceed with write

                if built is None:
                    built = build_dataset(dataset)

                write_conn.register("_demo_src", built[table])
                try:
                    write_conn.execute(
                        f"COPY (SELECT * FROM _demo_src) TO '{uri}' (FORMAT parquet)"
                    )
                    written[table] = uri
                finally:
                    try:
                        write_conn.unregister("_demo_src")
                    except Exception:
                        pass
    finally:
        write_conn.close()

    return written


# ---------------------------------------------------------------------------
# Datastore config factories
# ---------------------------------------------------------------------------


def s3_datastore_config(
    project_id: str,
    bucket: str | None = None,
) -> dict[str, Any]:
    """``duckdb`` datastore config reading all 17 demo tables from S3 parquet.

    One ``CREATE VIEW`` per table over ``read_parquet(s3://...)`` so the normal
    connector → /query → /data-browser pipeline picks every table up.  The
    httpfs/S3 SECRET is configured automatically at query time when ``s3://``
    references are detected (``setup_s3_httpfs`` resolves the credentials from
    environment variables — no plaintext secrets in the datastore row).
    """
    bucket = bucket or _s3_bucket()

    view_statements: list[str] = []
    for dataset, tables in DATASET_TABLES.items():
        for table in tables:
            uri = _parquet_s3_uri(project_id, dataset, table, bucket)
            view_statements.append(
                f"CREATE OR REPLACE VIEW {table} AS SELECT * FROM read_parquet('{uri}')"
            )

    return {
        "connector_type": "duckdb",
        "database": ":memory:",
        "view_sql": ";\n".join(view_statements),
        "description": (
            "Per-project demo datasets (retail sales, SaaS metrics, web analytics, "
            "finance ops) backed by S3 parquet files."
        ),
        "demo_project_id": project_id,
        "demo_s3_bucket": bucket,
        "sample": True,
        # Internal: backs the demo dashboards/queries by id. The connectors list
        # surfaces the branded virtual "Demo data" connector instead of this raw
        # row, so flag it system so list_connectors hides it (no duplicate card).
        "system": True,
    }


def datastore_config(db_path: str) -> dict[str, Any]:
    """Connector config for the read-only DuckDB demo datasource (local-file path).

    Legacy offline variant kept for ``seed.py --demo``'s local fallback.
    ``app/sample.py`` uses the parquet-backed configs above instead.
    """
    return {
        "connector_type": "duckdb",
        "database": db_path,
        "read_only": True,
        "description": "Bundled demo datasets (read-only DuckDB file).",
        # Internal: see s3_datastore_config — hidden from the connectors list so
        # the branded virtual "Demo data" connector is the only demo card.
        "system": True,
    }
